### ISSUE TITLE
Versions based on Blender 2.8 are not backward compatible

### ISSUE THREAD

**Issue by fufu5084** [snuq/Script-Shortcut#2]
Thanks for writing and sharing this useful Add-on! I just made a donation.

I was wondering if you'd be willing to indicate (reference this commit) in your latest readme.md?
I have Blender 2.78a which doesn't work with ScriptShortcut.py updated to work with Blender 2.8.

I downloaded this commit and it runs fine.

Or, if it's not too much work to make the latest version of ScriptShortcut.py backward compatible with 2.78, that would be great.

**Comment by snuq** [comment]
Glad you like the addon, and thank you for the donation!

Which commit are you referring to?

Backwards compatibility isnt really a possibility because Blender 2.8 changed so much of the Python API.  However, the current master has had no changes to the addon aside from the ones necessary to get it working in 2.8.  You can still download the last 2.79 version by selecting the 2.79 branch.

I think the latest 2.79 version worked with 2.78 as well, but I do not still have that version installed.  If it doesn't work, let me know and I'll see what I can do to make a 2.78 branch.

**Comment by fufu5084** [comment]
Thanks for the reply. To clarify, this commit that I downloaded which predates the changes for 2.8 works fine on my 2.78 a instance of Blender. My suggestion was to add a note in the latest readme.md advising people using the older version of blender to use this particular commit instead of the latest.

**Comment by snuq** [comment]
Yeah, its a good idea, ive been adding the blender version to my other addons' readme files as im updating them, and ill add it to this one on the next update (dont really want to do a commit just for that)
