### ISSUE TITLE
Add variables to panel

### ISSUE THREAD

**Issue by mino159** [snuq/Script-Shortcut#5]
**Problem:**
I need to switch some things in blender with script based on a number, now I have workaround with custom properties, but when I do not have selected object with properties, it isn't showing in panel. 

**Solution I'd like:**
When editing panel now you have Button, Spacer and Label, you can add another type - Variable, when you create it, you can reference it in a script and use it.

**Additional context**
here is how I use it now inside properties panel, it can be similar style as this.
![image](https://user-images.githubusercontent.com/18248865/184093221-de84d2cf-c915-4cca-a76f-0d6eb2f142b5.png)
![image](https://user-images.githubusercontent.com/18248865/184093064-46c45bdc-ab2b-4644-ab46-b3c34d712770.png)

**Comment by snuq** [comment]
Its a good idea, and I did want to do this actually, but the implementation is rather complex.  
Buttons are easy since I can just create one custom button that changes depending on how its used.  To do this with properties, it would require dynamic registering/unregistering of properties, which would require creating custom propertygroups on the fly.  I'm honestly not sure if this is actually possible.

Ill keep it in mind for the future, but im afraid this is more than I can do for now.
